name: Update Server IPs

on:
  push:
    paths:
      - src/constants/serverList.json
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 16.x
            cache: npm

      - run: npm i
      - name: Update server data
        run: |
          node src/printUpdatedServerAddresses.js > temp.json
          mv -f temp.json src/constants/serverList.json
          npx prettier --write src/constants/serverList.json

      - name: Sync changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update server ips" || true
          git push
